### ISSUE TITLE
Clarify steps for contributing blog posts

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiverse-trace.github.io#159]
I think the CONTRIBUTING guide for adding a blogpost can benefit from more detail to completely new users. I would suggest adding something like the following:

To submit a blog post, do the following:

- Make sure your main branch is up to date by running `git pull`
- Create a branch for the blog post.
- Create the blog post in a file called `index.qmd`, add it to a folder with a descriptive name, and put it in the `/posts/` folder. If there are references, add them to an `index.bib` file and put it in the same blog post folder.
- Stage and push your changes to your branch.
- Create a pull request with a descriptive title.
- Request reviews by tagging reviewers.
- Effect any requested changes.
- An admin merges when the post is ready.

**Comment by chartgerink** [comment]
Thanks @jamesmbaazam for opening up this issue and already adding a list of steps.

I will be writing a blog post next, so I'll use this for reference and open up a PR to add this information in the contributing guide as well 😊 Would you like me to invite you to review when I open this PR?
