### ISSUE TITLE
about the content in learn tab

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/epiverse-trace.github.io#183]
(...) Flagging that this change will likely be made obsolete by #157 though.

I expect this content to be part of the intro to the lesson materials instead. What do you think?

_Originally posted by @Bisaloo in https://github.com/epiverse-trace/epiverse-trace.github.io/issues/164#issuecomment-1893616115_

**Comment by avallecam** [comment]
brief issue to reply to this question.

I agree, that the structure of the workshop website is now within the lesson material structure of the workbench.

- How to participate? - (may be variable, depending on the event)
- What will you learn? - general learning outcomes can be more explicitly placed in the [summary](https://epiverse-trace.github.io/git-rstudio-basics/) side
- Who is this training for? - in [profiles](https://epiverse-trace.github.io/research-compendium/profiles.html) tab
- What is not included in this training? - this can also be placed in the [prereq](https://epiverse-trace.github.io/git-rstudio-basics/) section within the summary tab.
- Duration - (may be variable, depending on the event)
- Program - in the [instructors view](https://epiverse-trace.github.io/research-compendium/instructor/index.html) tab
- Materials you will need - in the [setup](https://epiverse-trace.github.io/git-rstudio-basics/#installing-git) section
- Materials we used - (may be variable depending on the event)
- Any questions? - in the learner view [index](https://epiverse-trace.github.io/research-compendium/#your-questions) page

For the event-dependent information, we can use a workshop page, relying on the [workshop-template](https://github.com/carpentries/workshop-template), like in the following [example](https://zedif.github.io/2023-06-13-ttt-online-CEST/).

This workshop page should include:
- how to book a place / how to join a waiting list / how to cancel
- session information: 
  - from xx:xx am to yy:yy am
  - session type: in-person or remote
  - venue
- general info (briefly summarizing bullet points or a subset of them for:)
  - aim
  - content
  - target audience
  - prerequisites / code of conduct 
  - learning outcomes

My follow-up question is: when this page may be needed, could the workshop page live in the epiverse-trace repository?

**Comment by avallecam** [comment]
> Yes, I agree. Sounds like a good plan 👍

actually, the question in the first comment is yours, hehe. my reply is in the following comment

**Comment by Bisaloo** [comment]
> My follow-up question is: when this page may be needed, could the workshop page live in the epiverse-trace repository? this would look like a gh-page deployed from a new repository https://epiverse-trace.github.io/2024-02-12-git-training, but not indexed within the main page. an alternative could also be to host it from the instructor's repository, as the carpentries seem to do, possibly because of potential overloading of event repos.

Yes, that's possible.

It may be easier from a maintainance point of view to have all this content in the main `tutorials` repo, which then dispatches to `tutorials-early`, `tutorials-middle` and `tutorials-late`. Is this not an option?

Happy to follow your final recommendation though. Both options are feasible from a technical point of view.

**Comment by avallecam** [comment]
Good to know that they are feasible.

> It may be easier from a maintenance point of view to have all this content in the main `tutorials` repo, which then dispatches to `tutorials-early`, `tutorials-middle` and `tutorials-late`. Is this not an option?

Yes, that is the approach for the general info and intro episode. 

To clarify, here I am visualizing a "workshop page" apart from any "lesson material":
- the "workshop page" will be event-specific (more focused on how to book, and session information -from, to, venue-), while 
- the "lesson material" will try to be as static as possible (all the workbench repos).

For that rationale, the "workshop page" may probably not be within the workbench repo, although I'll though about it when required.

With respect to the aim of the issue raised, I'll use the info registered here to display the mapped info to move it to the corresponding git repo. I'll close this and site it in the git repo in a different issue.
