### ISSUE TITLE
Add {simulist} to hex wall on Epiverse-TRACE website home page

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiverse-trace.github.io#187]
The hex wall towards the bottom of the Epiverse-TRACE homepage currently does not contain {simulist}. As this is a relatively stable and released package, I think now (or near-future) would be a good time to add it. 

Depending on whether we want to keep the number of hex logos constant, Pratik mentioned that {scenarios} can be removed as it is moving into an inactive state of development while still experiment. @pratikunterwegs are you still happy for this to be removed?

In terms of positioning, I think {simulist} should go next to {linelist} as an early task package. 

I'm happy to make a PR with these suggested changes, but wanted to make sure we all agree on the format and which hex logos to include.

**Comment by pratikunterwegs** [comment]
Yes, can be removed. We can always re-add it if development resumes.

**Comment by Bisaloo** [comment]
Yes please, a PR adding simulist at your recommended location and removing scenarios would be welcome.
