### ISSUE TITLE
add content for landing page for training materials

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/epiverse-trace.github.io#191]
Hi @chartgerink , the writing is now done for #157 . Please take a look at the shared Google Docs file.

I added one question about linking all dev-stage tags to [one lesson life cycle site](https://carpentries.github.io/lesson-development-training/lesson-design.html#iterative-development).

Once all are loaded, we should also request TRACE-LAC feedback on the description I made about Spanish materials.

**Comment by chartgerink** [comment]
Thanks @avallecam - given that there's still changes being made [in the doc](https://docs.google.com/document/d/1eYkripFEY_667Tc0wLJRoeUU7nQQy1kfRxUbeWXZMsQ/edit) I'll wait just a bit longer. Marked to take another look on Thursday 👍
