### ISSUE TITLE
how to communicate to participant about Event-specific information?

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/epiverse-trace.github.io#193]
from https://github.com/epiverse-trace/epiverse-trace.github.io/pull/157 I wonder if would be appropriate to isolate the showcase of "Learning materials" and "Event workshop page"

We briefly shared their different features at https://github.com/epiverse-trace/epiverse-trace.github.io/issues/183#issuecomment-1939388527

- "Learning material" trying to keep them as static as possible for reusability.
- "Event workshop page" with spatio-temporal event-specific information - how to book, from, to, venue, and feedback form.

Two alternatives I found about where this "Event workshop page" can live:

(1) An Event workshop page can be hosted within an organization page, for example:
- http://www.universe-hpc.ac.uk/events/upcoming-events/2024-02-29_seminar-imperial/

Action item: This may require the creation of a complementary tab called "Events".

(2) Also, this Event workshop page can be hosted elsewhere, examples:
- https://epimodelac.com/
- https://wmotion.github.io/2024-02-19-oxford/ (hosted by instructors)

This last example can use templates in English and Spanish (which we can adapt to our formats?):
- https://github.com/carpentries/workshop-template
- https://github.com/carpentries/workshop-template-es

Action item: This may require a subtitle within the current in-design "Learn" tab referring to "Workshops" ([as drafted in doc](https://docs.google.com/document/d/1eYkripFEY_667Tc0wLJRoeUU7nQQy1kfRxUbeWXZMsQ/edit))

This last one seems to be the most flexible. Happy to read more thoughts about this.

**Comment by avallecam** [comment]
tagging @lgbermeo for a follow-up discussion on the topic

**Comment by chartgerink** [comment]
To add a new page to the website, we'd need clearly articulated needs and benefits for adding it (and for whom). This will help identify the scope of this. Currently, I do not understand whether this suggestion would be for **organizers** or **participants**.

Given the title of this issue, I will assume it is a communication question around events to (potential) participants, so they can be informed and act upon that information (e.g., registration or providing feedback). In that case, I would suggest to keep it within what already exists and have more frequent communication in the form of blog posts (tagged with "Event").

**Comment by Bisaloo** [comment]
On a somewhat related note, just a reminder that Claudine created an [Epiverse calendar](https://view.monday.com/1267767805-fb40bb51c837164bf95532907829c3f8?r=euc1) last year that we should try to use and leverage more to advertise events to our community.

**Comment by avallecam** [comment]
> I will assume it is a communication question around events to (potential) participants, so they can be informed and act upon that information (e.g., registration or providing feedback)

Yes, accurate assumption. I can add more clarity to the issue title with this phrasing.

> I would suggest to keep it within what already exists and have more frequent communication in the form of blog posts (tagged with "Event").

Actually, I like this alternative. In Blog post entries we can use the cited templates with a link hosted in epiverse-trace repo. Event websites hosted elsewhere can also choose to create a blog entry if appropriate.

Given the Blog alternative, we can also suggest "Subscribe to our Blog RSS feed" next to the sign-in to the mailing list and follow us on twitter/X.

**Comment by chartgerink** [comment]
For the time being, we'll focus on adding blogs to announce events. Whenever a blog is added, you can add links in there as you wish @avallecam. This streamlines maintenance and allows us to gauge the need for an additional page more clearly.

Do you have what you need @avallecam for this issue to be closed? Documenting how to co-create the event calendar is important but potentially it's own issue.

**Comment by avallecam** [comment]
> Do you have what you need @avallecam for this issue to be closed?

Yes, I agree with using the blog to announce events. Thanks for the feedback! I'm closing this issue.
