### ISSUE TITLE
Automatically update `_freeze` when updating contributors list

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/epiverse-trace.github.io#196]
We update the contributors on the "About" page (`people.qmd`) on a regular basis, using GitHub actions. At the moment, this still requires updating the `_freeze` folder manually. 

It would be a good work action item to also automatically update the `_freeze` folder. Currently, we run `quarto render people.qmd` manually and commit the results - adding these steps to [the relevant action workflow](https://github.com/epiverse-trace/epiverse-trace.github.io/blob/main/.github/workflows/collect-contributors.yaml) would remove the need for that.

**Comment by Bisaloo** [comment]
Any reason we shouldn't put `freeze: false` for this specific file?

**Comment by chartgerink** [comment]
Fair question - I suspect the netlify deploy does not work if we do this, but let me try to make sure - this would be a nice way to address the issue 😊
