### ISSUE TITLE
Add acknowledgements section to automatic blog generation for pkg releases

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiverse-trace.github.io#197]
The addition of an Acknowledgements section at the end of blog posts for new package releases would be great to give visible credit to those participating in development, both on GitHub and not. Using `usethis::use_tidy_thanks()` should help automate the GitHub contributors.

**Comment by chartgerink** [comment]
Would you say this should only run since the last release (default behavior), since the beginning of the repo, or otherwise? 😊 

Happy to add this in as it queries the remote and does not need much additional handling from our end.

**Comment by joshwlambert** [comment]
In the release notes posts I manually add the GitHub username for all contributors to that specific release. Therefore, if someone is a package contributor but has not been involved in the latest release I do not include them in the acknowledgements. To me this is preferable so we do not get an ever-growing list of contributors, especially if contributions are small and in the distant past (if not it would be replicating the package contributor `ctb` in the `DESCRIPTION`). So I guess I like the default behaviour.

**Comment by chartgerink** [comment]
I looked into this and it is not as straightforward apparently - see also https://github.com/r-lib/usethis/issues/1998
