### ISSUE TITLE
Schedule blog posts

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/epiverse-trace.github.io#200]
We've had multiple blog posts come in rather quickly after one another recently. In a technical sense, that is not such an issue, but from the perspective of pacing the content this is problematic.

The risk is that we create highly irregular and volatile posting schedules (e.g.,, flooding with posts one month and then none for a while). This can reduce engagement with the content in the long run. 

Might it be an idea to think about ways to schedule these posts in the near future?

**Comment by Bisaloo** [comment]
Completely agree we can easily solve this here by having a publication schedule :100:.

For automated release posts, this needs to be addressed upstream IMO by having a package release calendar because delaying the release announcement doesn't really work once the release has been done.

**Comment by chartgerink** [comment]
Did a tiny bit of research on this, and it appears that the [`merge-schedule-action`](https://github.com/gr2m/merge-schedule-action) is a potential candidate. 

With this action, we would need to add a `/schedule <TIME>` in the original post of a PR. As far as I understand, it would not be possible to schedule based on a comment in the current form (however not confirmed at this time). Time is in ISO 8601 - for example `2024-04-01T09:00:00.000Z` for 9AM on April 1st 2024, UTC.

Another option I found, but is paid + expensive for organizations, is [PR scheduler](https://github.com/marketplace/pr-scheduler/plan/MLP_kgDNIY8#plan-8591). This would work through commands in the comments of a PR.
