### ISSUE TITLE
add a step-by-step guide on how to subscribe to the blog using RSS?

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/epiverse-trace.github.io#202]
**Is your feature request related to a problem? Please describe.**
Subscribing to RSS is not intuitive. I just did this during this project and looked for ways to get notifications from gh-discussions as reported in this entry https://github.com/orgs/epiverse-trace/discussions/82 

**Describe the solution you'd like**
Add a how-to guide for our audience using Feedbro as a browser add-in as one way to subscribe to the Blog and to the GH-Discussions tab

**Additional context**
I plan to use <https://scribehow.com/> which I already tried one week ago and looks like a simple way to create these how-to guides with online content only.

EDIT: this could be added as a link in the first line in https://epiverse-trace.github.io/blog

**Comment by chartgerink** [comment]
@avallecam Sorry to hear it was confusing - there was a time where this was much more commonly used and more straightforward. Great that you tried it out, regardless! 

A step by step guide is a bit much as we cannot be 100% complete on every single thing on the website. I also would stay away from advertising specific tools on the general pages. Regardless - I hear your need and **I will add a link to a resource where people can learn about RSS.**

That being said, I think a beginner's guide to RSS is great if you want to contribute it as a blog post. That is helpful for people and allows you to share your approach. I am confident this will be helpful to people!
