### ISSUE TITLE
`for` loops vs `apply()`

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/epiverse-trace.github.io#23]
[`apply()` is **not** faster than `for` loops if `for` loops are used correctly](https://privefl.github.io/blog/why-loops-are-slow-in-r/) but:

- less error-prone:
  - no variable leak
  - no risk of forgetting to initialize
- more compact (link to why this is good. neverworkintheory?)
- keep for loops exclusively for iterative situation -> easier to quickly identify / distinguish both situations

cc @pratikunterwegs

**Comment by pratikunterwegs** [comment]
Sorry, just seeing that I'm tagged here, approx 6 months after the fact. Unsure why I don't get notifications from some repos, but it's happened before.

I'm happy to take this up if it's still relevant.

**Comment by Bisaloo** [comment]
Thanks for your answer! In the mean time, I have already started working on this. I will try to push the draft soon and I can tag you for review if you're interested.

**Comment by pratikunterwegs** [comment]
Completely fair, happy to review
