### ISSUE TITLE
Standardise imperative tense in hex wall package descriptions

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiverse-trace.github.io#268]
I just noticed that the [package descriptions on the hex wall](https://github.com/epiverse-trace/epiverse-trace.github.io/blob/main/_data/epiverse_pkgs.csv) have a mix of tenses and could be standardized. The imperative tense would read more nicely, so I would suggest changing the descriptions of `{readepi}`, `{cleanepi}`, `{epichains}`, etc., to align with the others that already use that tense.

**Comment by chartgerink** [comment]
Thanks @jamesmbaazam for opening an issue - could you please add a example of the current language and the proposed one? This helps clarity on what you mean for those not as familiar with the grammar rules (my brain cannot parse grammar rules in any language for some reason 😅).

**Comment by jamesmbaazam** [comment]
Sure. 

Two examples that currently align with my suggestion are: 
- simulist : Simulate outbreak data
- serofoi : Estimate force of infection from serology

others that can be aligned:

package | Current description | Proposed change
---------|---------------------| ----------------
readepi | Tools for reading data | Import data
cleanepi | Tools for cleaning data | Clean imported data
ColOpenData | Open data for Colombia | ¯\_(ツ)_/¯
linelist | Tagging and validating individual data| Tag and validate individual data

**Comment by chartgerink** [comment]
Thanks @jamesmbaazam - appreciate the help 😄 I am happy to update this for consistency, and tagging @Bisaloo to see whether I am missing any context (maybe there's a [Chesterton fence](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence) I am not seeing).

**Comment by Bisaloo** [comment]
No reason. The text here was written during the early quick prototyping phase and I have no objections for it to be updated.

**Comment by jamesmbaazam** [comment]
> > maybe there's a [Chesterton fence](https://en.wikipedia.org/wiki/G._K._Chesterton#Chesterton's_fence)
> 
> As an aside, I really like this. I'm adding it to my collection of mental models.

@chartgerink I'm so sorry I mistakenly deleted your original comment that I was quoting 😭 . If it's not too much trouble, could you repost it?
