### ISSUE TITLE
Content request for "Getting started" page

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/epiverse-trace.github.io#272]
Hi 👋 I would like to request input on how we want people to get started using Epiverse. This issue is a tracker for that input.

Over in #262 we added a getting started page, but we are yet to provide people with a clear way to get started. How do we want to help newcomers to Epiverse? What does a successful start look like? I would love to get input on this to help make this a useful page.

**Comment by adamkucharski** [comment]
There could be parallels to a successful start with other tool collections, like tidyverse, pharmaverse etc. E.g. the UX probably needs to address main two user questions: what general range of problems can our tools solve? And which tool is most appropriate for the specific problem the user has?

I guess challenge is how to address these questions in a space-efficient way. Currently we've got that (quite rough) JS hover-over graphic of what's available, organised by the stage of outbreak people might want to analyse. But perhaps some brief summaries (a la [tidyverse](https://www.tidyverse.org/packages/)) or JS animation with illustrative questions would be more effective?

Then we'd obviously like more active and technically minded users to [engage more deeply](https://epiverse-trace.github.io/get-involved.html) once they've got a feel for what Epiverse is doing.
