### ISSUE TITLE
Benchmarking design decisions - an example with `cli::cli_warn()`

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiverse-trace.github.io#28]
I discovered that `cli::cli_warn()` is a slower alternative to `base::warning()` when throwing warnings. 

I have drafted a rough blog post on this by relating it to the use of benchmarking to weigh design decisions. 

Do let me know what you think.

**Comment by Bisaloo** [comment]
Thanks, it sounds like a very interesting topic! I agree it would be a good addition to the blog.

I remember seeing an issue somewhere (maybe one of the `r-lib` repos???) where it was the around way around in a sense. Some contributors suggested to remove the dependency on stringr to make the package more lightweight but the maintainer argued that base alternative were much slower. It could be good to reference / discuss it there as well if I can find it again.

**Comment by jamesmbaazam** [comment]
That's interesting. I will see if I can find it too.

I would be fine with being proven wrong. 

What is the best way to share the draft?

**Comment by Bisaloo** [comment]
> I would be fine with being proven wrong.

I don't think it would prove you wrong. Your conclusions are still valid. I just shows that benchmarks can either make you reject or want to keep a dependency. It's a really interesting discussion.

> What is the best way to share the draft?

As you prefer. Opening a PR is probably the simplest? But do what works best for you.

**Comment by jamesmbaazam** [comment]
Please find the rough draft [here](https://github.com/jamesmbaazam/blogposts/blob/main/epiverse_blogposts/benchmarking_design_decisions.qmd). I will transfer it here as a pull request once I feel it's ready.

**Comment by Bisaloo** [comment]
There are some useful elements here as well: https://yihui.org/en/2023/01/knitr-stringr/

**Comment by jamesmbaazam** [comment]
Thanks, Hugo. I took a break from writing this post because some other stuff took priority. I should get back to it asap.
