### ISSUE TITLE
Comparison of lifecycle frameworks

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/epiverse-trace.github.io#29]
- RECON
- `r-lib/lifecycle`
- repostatus
- package numbering

**Comment by joshwlambert** [comment]
Development of the blog post can be found at: https://joshwlambert.github.io/lifecycling/articles/comm_code_dev.html

Once I'm happy with the draft I will transfer it over to this package, make a pull request, and assign reviewers. 

Feel free to leave issues on the {lifecycling} package for input on the blog post while it's drafted.

**Comment by Bisaloo** [comment]
Something I'd love to see in this blog post would be a figure summarising a collaborative exercise we take as a team. Each team member would move the different stages on a time-directed axis and try to see which stage from one framework corresponds to another stage in another framework (I placed the badges randomly for this example):

![blogpost_lifecycle](https://user-images.githubusercontent.com/10783929/233014140-3c2fb72c-c589-46de-961b-689d0be66180.svg)

The outcome would be a figure overlapping the votes from each team member with a certain alpha value.

Then, we could think about things like: are certain frameworks more granular than others? Or do some focus more on earlier vs later stages? Or do they convey completely different information and they cannot really be compared?

Given what you have already written however, I'm afraid the post would become quite long so maybe we could split it in two parts.

What do you think?
