### ISSUE TITLE
Replace R terminal animation with illustration of what tools can do

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/epiverse-trace.github.io#292]
The new homepage is looking much better, but the current R terminal graphic doesn't clearly showcase what Epiverse tools can do, and is likely to be hard to interpret for many visitors (as well as creating quite a lot of blank space on the page).

Would suggest we instead include a graphic with visual outputs and pseudo code to illustrate package loading. Very rough example below – could expand to showcase 3-5 new packages across the project.

![epiverse_animation](https://github.com/epiverse-trace/epiverse-trace.github.io/assets/8329046/c2340282-171a-4189-b6e4-84ccb50bd4a9)

**Comment by juan-umana** [comment]
Hi @adamkucharski ! Totally agree, from our experience showcasing epiverse-trace with users they expect to see implementation, cases of use, and viz resources before code aspects (Endemic channel is a great example, thanks for include it!). As a welcoming strategy, we think that the R terminal is not very user-friendly.

**Comment by Bisaloo** [comment]
Fix by #295
