### ISSUE TITLE
Blog category filters not working

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/epiverse-trace.github.io#330]
For some reason, the blog categories do not display properly when selected. 

https://github.com/user-attachments/assets/913ded93-03d5-4267-85e9-dfc5910ad890

I works without issue when navigating the [Resources](https://epiverse-trace.github.io/resources.html), and the blog categories filter works when testing the page locally. I am not sure what is happening here at the moment, but it will require some attention to fix.

**Comment by joshwlambert** [comment]
When I click on the dropdown `News`, both `Blog - Articles` and `Blog - Release notes` don't show any results on the page.

<img width="1512" alt="Screenshot 2024-11-22 at 09 56 56" src="https://github.com/user-attachments/assets/4971a2d6-a963-443b-85c4-f939532d1d4e">

I predict for the same reason as the tags.

**Comment by chartgerink** [comment]
Thanks @joshwlambert – i am not sure what is happening as my local version works without issue. Is anyone able to reproduce this locally with running `quarto render`?

**Comment by Bisaloo** [comment]
This is where it happened: https://github.com/epiverse-trace/epiverse-trace.github.io/commit/e133589af3761414979936de7fc67e7cdd967abb. It may be related to the switch quarto 1.6.30 -> 1.6.32
