### ISSUE TITLE
Awkward rendering of blogpost

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiverse-trace.github.io#57]
The blogpost on extending data.frames has an awkward code block appearing before the introduction. Is that a desired effect? I think you probably forgot to hide [this code chunk](https://github.com/epiverse-trace/epiverse-trace.github.io/blob/5090a59313813f0267c59d2bf1f175b438aa5d25/posts/extend-dataframes/index.qmd#LL14C30-L14C30).

**Comment by joshwlambert** [comment]
@jamesmbaazam thanks for pointing this out.

I personally prefer to see the library calls at the start of vignettes as it makes it clear which packages are being used, and prevents several packages being loaded at different points in the post/vignette.  

Given this is a single `library()` call, and is specifically relevant for the section "Compatibility with {dplyr}" I'll make a change to move it to that section.

**Comment by joshwlambert** [comment]
Change made in #58.

**Comment by jamesmbaazam** [comment]
Thanks for your thoughts. It's funny because I initially thought it was a banner of some sort to accompany the post until I found out it was a code chunk. I wasn't suggesting at all that it be hidden. I thought it was a misplaced rendering issue and didn't take the time to look at the order of rendering. In this case, I like the change in #58 for the reason that it enters the story exactly where it's needed. I personally prefer to load the packages as they become part of the story. However, as is obvious, it's all a matter of style.
