### ISSUE TITLE
Contribution guide: Clarify use of R code 

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/epiverse-trace.github.io#93]
In the contribution guide, the section on [pure quarto](https://github.com/epiverse-trace/epiverse-trace.github.io/blob/main/.github/CONTRIBUTING.md#pure-quartomarkdown-syntax) is not clear to me. How should we insert executable R code? I'm asking because the argument in that section is that it introduces a dependency on R. Why is that an issue?

**Comment by Bisaloo** [comment]
It's fine to insert executable R code if you want to demonstrate something in R. However, you should not use R code to do things that be done using standard / markdown standard syntax (e.g., insert images).

If you have a suggestion to improve the phrasing and clarify that R code is perfectly fine when needed, please submit a PR.

**Comment by jamesmbaazam** [comment]
Sorry, I missed this.
