### ISSUE TITLE
Add easy way to get the RSS feed links

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/epiverse-trace.github.io#97]

**Comment by chartgerink** [comment]
Would you mind expanding on what this means if it is still relevant? I am having a tough time seeing whether I can support on this one 😅

**Comment by Bisaloo** [comment]
The site currently provides a couple of different RSS feeds, defined here:

https://github.com/epiverse-trace/epiverse-trace.github.io/blob/74ccd19694850f868254cc621cc7769a2c51ee23/blog.qmd#L10-L11

https://github.com/epiverse-trace/epiverse-trace.github.io/blob/74ccd19694850f868254cc621cc7769a2c51ee23/presentations.qmd#L10

But these feeds are not advertised anywhere. It would be good to add a short sentence or icon somewhere to let visitors know we provide RSS feeds, and they can subscribe to them.
